### wien2wannier/test/Makefile
###
###    wien2wannier/test/Makefile
###
### Copyright 2016 Elias Assmann

-include ../make.sys

SUBDIRS := PoC repl

.PHONY: all clean $(SUBDIRS) dist

all: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@

## Time-stamp: <2016-07-13 16:22:37 assman@faepop71.tu-graz.ac.at>
