#!/bin/bash
if [ $# -eq 3 ]; then
   seed=$1
   save=$2
   iter=$3
# elif [ $# -eq 2 ] && [ "$1" == "-restore" ]; then
   
# elif [ $# -eq 3 ] && [ "$1" == "-restart" ]; then
   
elif [ $# -eq 1 ] && [ "$1" == "-h" ]; then
      echo "Usage: restore_woptic case savename <#iterationstorestore>"
      exit 0
fi

# cp $seed.kgen $seed.kgen0
# cp $seed.kgen_full $seed.kgen_full0
# cp $seed.klist $seed.klist0
# cp $seed.klist_full $seed.klist_full0

 for ((  i = 1 ;  i <= $iter;  i++  )) do
  cp $save.optcondw$i $seed.optcondw$i
  cp $save.woptoutw$i $seed.woptoutw$i
  cp $save.klist$i $seed.klist$i
  cp $save.klist_refined$i $seed.klist$i
  cp $save.kgen$i $seed.kgen$i
  cp $save.klist_full$i $seed.klist_full$i
  cp $save.kgen_full$i $seed.kgen_full$i
  cp $save.kcontribw$i $seed.kcontribw$i
  cp $save.ham_fine$i $seed.ham_fine$i
  cp $save.voe$i $seed.voe$i
  cp $save.win$i $seed.win$i
  cp $save.wdosw$i $seed.wdosw$i
  cp $save.K1w$i $seed.K1w$i
  cp $save.wdoskcontribw $seed.wdoskcontribw$i
  cp $save.mommat$i $seed.mommat$i
  cp $save.woptin $seed.woptin
 done
# # cp $seed.klist $seed.klist2
# # x lapw1 #work with klist
# # x optic #work with klist
# # write_win -renew $seed
# # wannier90.x $seed
# # ../optics_tetra $seed
# # cp $seed.kcontrib $seed.kcontrib2
# # cp $seed.optcondw $seed.optcondw2
# # cp $seed.woptoutw $seed.woptoutw2
