#!/bin/bash
#
# w2wsp
# P.Wissgott 10/01/10

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
   echo "Usage: w2wsp -up/-dn/-so case"
   exit
elif [ $# -eq 1 ] && [ "$1" == "-h" ]; then
   echo "computes input for wannier90 from a wien2k computation."
   echo "Usage: w2wsp -up/-dn/-so case"
   echo "Requires 6 files:"
   echo "   1) case.w2win[up/dn/so]: initial projections"
   echo "   2) case.vector[up/dn/soup/sodn]: eigenvectors"
   echo "   3) case.energy[up/dn/soup/sodn]: eigenenergies"
   echo "   4) case.vsp[up/dn]: potential"
   echo "   5) case.struct" 
   echo "   6) case.nnkp: nearest neighbor k-points"
   echo "Produces 3 (main) files:"
   echo "   1) case.mmn[up/dn]: k-space overlaps"
   echo "   2) case.amn[up/dn]: initial overlaps"
   echo "   3) case.eig[up/dn]: eigenvalues at k-points(band energies)"
   echo "Note: using the "-so" option will run w2w for both up and dn spin"
   echo "      and automatically combine the output to case.mmnso and case.amnso"
   echo "Note: whether real or complex version is used is determined by"
   echo "the case.dayfile file(if present)"
   exit 0
fi

if [ $# -eq 1 ]; then
   echo "Warning: start non spin-polarized version of w2w"
   SEEDNAME=$1
   w2w $SEEDNAME
elif [ $# -eq 2 ]; then
   if [ "$1" == "-up" ]; then
      SEEDNAME=$2
      w2wup $SEEDNAME
      
    elif [ "$2" == "-up" ]; then
       SEEDNAME=$1
       w2wup $SEEDNAME
   
    elif [ "$1" == "-dn" ]; then
      SEEDNAME=$2
      w2wdn $SEEDNAME

    elif [ "$2" == "-dn" ]; then
       SEEDNAME=$1
       w2wdn $SEEDNAME

    elif [ "$1" == "-so" ]; then
       SEEDNAME=$2
       echo "++ w2w for spin-orbit calculation ++"
       write_w2wdef -soup $SEEDNAME
       w2wc w2w.def
       echo "++ w2w done for spin up component ++"
       write_w2wdef -sodn $SEEDNAME
       w2wc w2w.def
       echo "++ w2w done for spin dn component ++"
       echo "++ add up spin components ++"
       combine_spinfiles $SEEDNAME
       
    elif [ "$2" == "-so" ]; then
       SEEDNAME=$1
       echo "++ w2w for spin-orbit calculation ++"
       write_w2wdef -soup $SEEDNAME
       w2wc w2w.def
       echo "++ w2w done for spin up component ++"
       write_w2wdef -sodn $SEEDNAME
       w2wc w2w.def
       echo "++ w2w done for spin dn component ++"
       echo "++ add up spin components ++"
       combine_spinfiles $SEEDNAME
       
    else
       echo "Error: Unknown option"
       exit 0
    fi
fi




