#!/bin/bash
#
# wplot script for SO calc.
# P.Wissgott 10/01/10

if [ $# -eq 1 ] && [ "$1" == "-h" ]; then
   echo "calculates Wannier orbitals in real space for plotting(spin-orbit. version)"
   echo "Usage: wplotso -up/-dn case [idx_wann]"
   echo "if the optional input idx_wann is given, the Wannier function"
   echo "with this index is plotted, otherwise the index is taken from"
   echo "the case.wplotin file."
   echo "Requires 7 files:"
   echo "   1) case.wplotin[up/dn]: real space mesh vectors"
   echo "   2) case.chkso: U matrices from wannier90"
   echo "   3) case.vector[soup/sodn]: eigenvectors"
   echo "   4) case.energy[soup/sodn]: eigenenergies"
   echo "   5) case.vsp[up/dn]: potential"
   echo "   6) case.struct" 
   echo "   7) case.w2win[up/dn]: w2w input file"
   echo "Produces 2 (main) files:"
   echo "   1) case.psink[up/dn]: |w(r)|^2 for real space mesh"
   echo "   2) case.psiarg[up/dn]: phi(w(r)) phases on real space mesh"
   echo "Note: whether real or complex version is used is determined by"
   echo "the case.dayfile file(if present)"
   exit 0
fi

if [ "$1" == "-up" ]; then
  SP="up"
elif [ "$1" == "-dn" ]; then
  SP="dn"
else
  echo "Please specify spin component"
  echo "Usage: wplotso -up/-dn case [idx_wann]"
  exit
fi

SEEDNAME=$2

if [ $# -eq 3 ]; then
  IDX_WANN=$3
else 
  IDX_WANN=0
fi

write_wplotdef "-so""$SP" $SEEDNAME
wplot $SEEDNAME $IDX_WANN

