#!/bin/bash
#
# wplot main script
# P.Wissgott 10/01/10

if [ $# -lt 1 ]; then
   echo "Usage: wplot case [idx_wann]"
   exit
elif [ $# -eq 1 ] && [ "$1" == "-h" ]; then
   echo "calculates Wannier orbitals in real space for plotting"
   echo "Usage: wplot case [idx_wann]"
   echo "if the optional input idx_wann is given, the Wannier function"
   echo "with this index is plotted, otherwise the index is taken from"
   echo "the case.wplotin file."
   echo "Requires 7 files:"
   echo "   1) case.wplotin: real space mesh vectors"
   echo "   2) case.chk: U matrices from wannier90"
   echo "   3) case.vector: eigenvectors"
   echo "   4) case.energy: eigenenergies"
   echo "   5) case.vsp: potential"
   echo "   6) case.struct" 
   echo "   7) case.w2win: w2w input file"
   echo "Produces 2 (main) files:"
   echo "   1) case.psink: |w(r)|^2 for real space mesh"
   echo "   2) case.psiarg: phi(w(r)) phases on real space mesh"
   echo "Note: whether real or complex version is used is determined by"
   echo "the case.dayfile file(if present)"
   exit 0
fi

SEEDNAME=$1
#write_wplotdef $SEEDNAME
if [ $# -eq 2 ]; then
  IDX_WANN=$2
else 
  IDX_WANN=0
fi
 
if [ -f "$SEEDNAME"".dayfile" ]
then
  tmp="$(grep "lapw2 -c" "$SEEDNAME.dayfile")"
  if [ -z "$tmp" ]; then
      wplotr wplot.def $IDX_WANN
  else
      wplotc wplot.def $IDX_WANN
  fi
else

  echo -n " Did not find $SEEDNAME.dayfile. Start real or complex(no inversion symmetry) version of wplot? [r/c]  "
  read answer
  if [[ $answer = "r" ]]; then
     wplotr wplot.def $IDX_WANN
  elif [[ $answer = "c" ]]; then
     wplotc wplot.def $IDX_WANN
  else
    echo "Please type [r](real) or [c](complex)"
    exit 0
fi

fi